### ISSUE TITLE
failing tests on a clean clone

### ISSUE THREAD

**Issue by SimonCropp** [JDCain/Xunit.Extensions.TestDependency#5]
running the tests with no changes gives 10 failures. do they pass on your machine and the build server?

**Comment by JDCain** [comment]
I confirmed they were passing at this commit: 2db9203
They do run in multiple frameworks so it should show 36 tests total.
If I use netstandard there are issues with xunit.extensiblity.core where it will not work when added to a classic .net project

![image](https://user-images.githubusercontent.com/7768533/72183806-e958ca80-33bc-11ea-86ab-1e35df02ff0e.png)
